name: Test FastAPI Docker Image

on:
  push:
    branches: [main]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker image from GHCR
        run: docker pull ghcr.io/romainb35/bert-fastapi-cpu:latest

      - name: Run container
        run: docker run -d -p 8000:8000 --name bert-api ghcr.io/romainb35/bert-fastapi-cpu:latest

      - name: Wait for API to start
        run: |
          for i in {1..10}; do
            curl -s http://localhost:8000/ && break
            echo "Waiting for API..."
            sleep 3
          done

      - name: Run test scripts
        run: |
          chmod +x dockerfiles/bert-fastapi-cpu/tests_scripts/*.sh
          ./dockerfiles/bert-fastapi-cpu/tests_scripts/test_api_root_endpoint.sh
          ./dockerfiles/bert-fastapi-cpu/tests_scripts/test_api_predict_endpoint.sh
          ./dockerfiles/bert-fastapi-cpu/tests_scripts/test_api_predict_batch_endpoint.sh

      - name: Stop and remove container
        run: docker stop bert-api && docker rm bert-api

